import React, { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, EyeOff, Fingerprint, Vote } from 'lucide-react';
import { playCountdown, playWhoosh, triggerHaptic } from '../utils/soundEffects';

export const GameOnboarding = ({ onComplete, onSkip }: { onComplete:()=>void; onSkip:()=>void }) => {
  const [step,setStep]=useState(0); const [revealed,setRevealed]=useState(false); const [progress,setProgress]=useState(0); const timer=useRef<number>();
  useEffect(()=>()=>window.clearInterval(timer.current),[]);
  const finish=()=>{localStorage.setItem('cipher_has_completed_onboarding','true');onComplete();};
  const next=()=>{playWhoosh();if(step<2)setStep(value=>value+1);else finish();};
  const beginHold=()=>{const started=performance.now();window.clearInterval(timer.current);timer.current=window.setInterval(()=>{const next=Math.min(100,(performance.now()-started)/6);setProgress(next);if(next>=100){window.clearInterval(timer.current);setRevealed(true);triggerHaptic([30,20,60]);}},16);};
  const conceal=()=>{window.clearInterval(timer.current);setProgress(0);setRevealed(false);};
  return <div className="onboarding-case mx-auto flex min-h-[calc(100dvh-69px)] w-full max-w-lg flex-col px-5 pb-6 pt-4">
    <header className="flex items-center justify-between"><span className="cipher-eyebrow">Briefing {step+1} / 3</span><button onClick={()=>{localStorage.setItem('cipher_has_completed_onboarding','true');onSkip();}} className="cipher-text-button">Skip</button></header>
    <div className="briefing-progress mt-3">{[0,1,2].map(item=><span key={item} className={item<=step?'active':''}/>)}</div>
    <main className="flex flex-1 flex-col justify-center py-6">
      {step===0&&<section className="briefing-page"><div className="cipher-seal" aria-hidden="true"><i/></div><p className="cipher-eyebrow mt-8">A word game for suspicious friends</p><h1 className="mt-3 font-display text-6xl font-black leading-[.88] tracking-[-.07em]">Everyone knows.<br/>Almost.</h1><p className="mt-6 max-w-sm text-base font-semibold leading-7 text-[var(--muted)]">Share one phone, give careful clues, and find who received the wrong word before they work out yours.</p><div className="table-diagram mt-8" aria-hidden="true">{[0,1,2,3,4,5].map(item=><i key={item}/>)}</div></section>}
      {step===1&&<section className="briefing-page text-center"><EyeOff className="mx-auto h-8 w-8"/><p className="cipher-eyebrow mt-5">Practice the private reveal</p><h1 className="mt-3 font-display text-4xl font-black">Hold it. See it. Release.</h1><p className="mx-auto mt-3 max-w-xs text-sm leading-6 text-[var(--muted)]">Every role uses the same neutral screen so color and brightness cannot give anyone away.</p><div className="practice-secret mt-7"><small>{revealed?'Sample word':'Secret concealed'}</small><strong>{revealed?'COFFEE':'••••••'}</strong></div><button onPointerDown={event=>{event.currentTarget.setPointerCapture(event.pointerId);beginHold();}} onPointerUp={conceal} onPointerCancel={conceal} className="reveal-hold mt-5 touch-none"><span className="reveal-hold-fill" style={{transform:`scaleX(${progress/100})`}}/><Fingerprint className="relative h-6 w-6"/><span className="relative">{revealed?'Release to hide':progress?'Keep holding':'Press and hold'}</span></button></section>}
      {step===2&&<section className="briefing-page"><div className="clue-loop"><div><span>01</span><strong>Clue</strong><small>Prove you know the word.</small></div><div><span>02</span><strong>Suspect</strong><small>Listen for a careful bluff.</small></div><div><span>03</span><strong>Vote</strong><small>Confirm before locking it.</small></div></div><div className="countdown-demo mt-8"><span>3</span><span>2</span><span>1</span><strong onClick={()=>playCountdown(0)}>GO</strong></div><h1 className="mt-7 font-display text-4xl font-black">The table does the rest.</h1><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Cipher handles turns, timing, private ballots, fresh words, and the rematch.</p></section>}
    </main>
    <footer className="grid grid-cols-[auto_1fr] gap-2">{step>0?<button onClick={()=>setStep(value=>value-1)} className="cipher-button-secondary px-4"><ArrowLeft className="h-4 w-4"/>Back</button>:<span/>}<button onClick={next} className="cipher-button-primary">{step===2?<><Vote className="h-4 w-4"/>Choose a game</>:<>Continue<ArrowRight className="h-4 w-4"/></>}</button></footer>
  </div>;
};
